baseURL: https://hugo-toha.github.io

languageCode: jp-ja
title: "Nave-wataのブログ"

# Use Hugo modules to add theme
module:
  imports:
  - path: github.com/hugo-toha/toha/v4

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  jp:
    languageName: Japanese
    weight: 1

# Force a locale to be use, really useful to develop the application ! Should be commented in production, the "weight" should rocks.
DefaultContentLanguage: jp

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
    - HTML
    - RSS
    - JSON

# Enable global emoji support
enableEmoji: true

# Site parameters
params:

  # GitHub repo of your site
  gitRepo: https://github.com/Nave-wata/nave-wata.github.io
  # Default branch of your Git repo
  gitBranch: main

  # Configure various features of this theme
  features:

    # Enable Analytics
    analytics:
      enabled: false

  # Provide footer configuration.
  footer:
    enable: true
    
    # Show/hide newsletter section in the footer. Default is "true".
    # Currently, it supports "mailchimp".
    newsletter:
      enable: false