baseURL: https://hugo-toha.github.io

languageCode: jp-ja
title: "Nave-wata ブログ"

# Use Hugo modules to add theme
module:
  imports:
  - path: github.com/hugo-toha/toha/v4

# Site parameters
params:

  # GitHub repo of your site
  gitRepo: https://github.com/Nave-wata/nave-wata.github.io
  # Default branch of your Git repo
  gitBranch: main

  # Configure various features of this theme
  features:

    # Enable Analytics
    analytics:
      enabled: false

  # Provide footer configuration.
  footer:
    enable: true
    
    # Show/hide newsletter section in the footer. Default is "true".
    # Currently, it supports "mailchimp".
    newsletter:
      enable: false